# -*- coding: utf-8 -*-
"""Adivinhacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EDpclAosDY4GcrD_IGDiXbngz5HIGR9Q
"""

def jogar():
  from random import randint

  print_initialize_message()

  ask_level()
    
  score = 1000
  total_score = score

  check_selected_level()

  secret_number = randint(0,20)

  print("Número para acertar ",secret_number)

  for round in range(1, number_attempts + 1):
    print("Tentativa {} de {}".format(round,number_attempts))
    shot = int(input("Tente adivinhar: "))
    print("Você chutou: ", shot)

    hit = shot == secret_number
    higher = shot > secret_number
    lower = shot < secret_number
    dif_shot_secret = shot - secret_number
    

    if (hit):
      print("Você acertou!")
      break

    elif (higher):
      print("Você errou! Seu palpite foi maior que o número secreto")
      total_score = total_score - abs(dif_shot_secret)


    elif (lower):
      print("Você errou! Seu palpite foi menor que o número secreto")
      total_score = total_score - abs(dif_shot_secret)


  if (hit):
    print("Você VENCEU!")
    print("Sua pontuação foi {}".format(abs(total_score)))
  else:
    print("Você gastou todas suas tentativas! =(")

def print_initialize_message():
  print('******************************')
  print('**   Jogo de Adivinhação    **')
  print('******************************')
  print("**         Níveis           **")
  print("**  Nível 1 = 20 tentativas **")
  print("**  Nível 2 = 10 tentativas **")
  print("**  Nível 3 = 5 tentativas  **")
  print("**  Tente acertar de 0 a 20 **")
  print('******************************')

def ask_level()
    level = int(input("Escolha o nível: "))

  while level > 3:
    if level > 3:
      level = int(input("Nível inválido digite novamente: "))

def check_selected_level():
  if level == 1:
    number_attempts = 20
  elif level == 2:
    number_attempts = 10
  elif level == 3:
    number_attempts = 5