
# -*- coding: utf-8 -*-
"""Forca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jzT9gz5AHOtwP3mAxucz8FJWhgkrJ7RH
"""

def jogar():

  import random

  print_message_opening()

  secret_word = load_secret_word()

  hitted_letters = initialize_hitted_words(secret_word)

  hit = False
  hanged = False
  misses = 6

  print(hitted_letters)

  while (not hit and not hanged):

    shot = ask_shot()

    if (shot in secret_word):
      mark_correct_shot(shot, hitted_letters, secret_word)
    else:
      misses -= 1
    
    hanged = misses == 0
    hit = '_' not in hitted_letters

    print(hitted_letters)
    print('Você tem mais {} chances'.format(misses))

  if (hit):
    print_message_winner()
  else:
    print_message_loser()

  print('Fim do jogo')


def print_message_opening():

  print('*********************************')    
  print('***Bem vindo ao jogo da Forca!***')   
  print('*********************************')

def load_secret_word():

  import random

  file = open('palavras.txt', 'r')
  words = []

  with open('palavras.txt') as file: 
    for row in file:
      row = row.strip()
      words.append(row)

  number = random.randrange(0, len(words))
  secret_word = words[number].upper()
  
  return secret_word

def initialize_hitted_words(secret_word):
 return ['_' for letter in secret_word]

def ask_shot():
  shot = input('Qual letra?')
  shot = shot.strip().upper()
  return shot

def mark_correct_shot(shot, hitted_letters, secret_word):
  position = 0
  for letter in secret_word:
    if (shot.upper() == letter.upper()):
      hitted_letters[position] = letter
    position +=1

def print_message_winner():
  print('Parabéns, você ganhou!!')
def print_message_loser():
  print('Puxa, você foi enforcado!!')
  print('A palavra era {}'.format(secret_word))
