# -*- coding: utf-8 -*-
"""forca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jzT9gz5AHOtwP3mAxucz8FJWhgkrJ7RH
"""

def jogar():
  print('*********************************')    
  print('***Bem vindo ao jogo da Forca!***')   
  print('*********************************')

  secret_word = 'banana'
  hitted_letters = ['_',	'_',	'_',	'_',	'_',	'_']

  hit = False
  hanged = False
  misses = 6

  print(hitted_letters)
  print('*********************************')

  while (not hit and not hanged):
    
    shot = input('Qual letra?')

    if (shot in secret_word):
      position = 0
      for letter in secret_word:
        if (shot.upper() == letter.upper()):
          hitted_letters[position] = letter

        position += 1

    else:
      misses -= 1
      
    hit = '_' not in hitted_letters
    hanged = misses == 0
    print(hitted_letters)
    print('Você tem mais {} chances'.format(misses))

  if (hit):
      print('Você ganhou!!')
  else:
      print('Você perdeu!!')
  print('Fim do jogo')

jogar()